version: '3.3'

services:
  provident_web:
    build: .
    container_name: provident_page
    restart: always
    deploy:
      resources:
        limits:
          memory: 250M
    ports: 
      - 8000:8000
    volumes:
      - .:/home/provident_page
    networks:
      red_provident:
        ipv4_address: 192.168.121.20
    command: python manage.py runserver 0.0.0.0:8000


networks:
    red_provident:
        ipam:
            config:
              - subnet: 192.168.121.0/24